import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { tw } from '@/utils/tw'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header
          className={tw(
            //
            'bg-slate-900',
            'text-white',
            'p-4',
            'text-center',
          )}
        >
          <h1 className={'text-3xl font-semibold'}>Mark2Html Converter</h1>
        </header>
        {children}
      </body>
    </html>
  )
}
