import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import './globals.css'
import { tw } from '@/utils/tw'

const sans = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mark2Html Converter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={sans.className}>
        <header
          className={tw(
            //
            'bg-slate-900',
            'text-white',
            'p-4',
            'text-center',
          )}
        >
          <h1
            className={tw(
              //
              'text-2xl',
              'md:text-3xl',
              'font-semibold',
            )}
          >
            Mark2Html Converter
          </h1>
        </header>
        {children}
      </body>
    </html>
  )
}
